name: run-glualint
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  Lint:
    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml@master
    with:
      config: ".glualint.json"
